### ISSUE TITLE
[1.10.2] Forestry support not working?

### ISSUE THREAD

**Issue by Kiyaku** [jaredlll08/ModTweaker#432]
#### Issue Description:
Trying to add recipes to some of the forestry machines. No errors occur so i assume the format is correct (if i try to mess it up on purpose, it does print out errors) but none of the recipes seem to work. They do not show up in JEI and just trying to craft it anyway doesn't work. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

http://pastebin.com/JzdSmLmj

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

http://pastebin.com/cPyRUUbf

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Crafttweaker: 3.0.22
- ModTweaker: 2.0.9
- MTLib: 1.0.1

#### Your most recent log file where the issue was present: 

http://pastebin.com/AJEVcE2A

**Comment by SOL3675** [comment]
I had same situation.
I tried to add carpenter's recipes, but it won't work.
Here is my script.
mods.forestry.Carpenter.addRecipe(<forestry:fabricator>, [[<ore:plateGold>, <ore:plateBrass>, <ore:plateGold>], [<ore:plateBrass>, <forestry:hardenedMachine>, <ore:plateBrass>],[<ore:ingotGold>, <actuallyadditions:blockGiantChest>, <ore:ingotGold>]], 100, <liquid:water> * 2000,  <minecraft:diamond>);
I got no error as Kiyaku said and use the same versions of the mods.

**Comment by SOL3675** [comment]
So, I read #424 and built from the master (Download date: 2/27).
Using this built, the carpenter's recipe works fine, but not shown in JEI.
Could you update JEI entry of Forestry?
http://imgur.com/xr52R3v

**Comment by jaredlll08** [comment]
When I get time, I'll reconsider that PR and make the changes to it to make it work

**Comment by SOL3675** [comment]
Thanks, anyway.

**Comment by SOL3675** [comment]
I also tried to add the recipe of Thermionic Fabricator using the built above, but the error occurred.
Script : http://pastebin.com/1PYu99GT
Error log : http://pastebin.com/iWwXyUKD

**Comment by jaredlll08** [comment]
This should be fixed no

**Comment by Kiyaku** [comment]
Downloaded the latest CraftTweaker/MTLib/Modtweaker, but it's still an issue. Also updated to the latest forge. 

Minetweaker log: http://pastebin.com/5eiZbMTA 
Client log: http://pastebin.com/TjkwvCcA
Script: http://pastebin.com/d4uqCeBL 

It does not show my new recipes nor do they work (i can't enter the new items i added into those machines). 
I tried to remove the cocoa bee comb from the centrifuge too, it does not allow me to put it into the machine then, but JEI still shows it. 

Let me know if i can provide anything else.

**Comment by jaredlll08** [comment]
I meant "now" as in I just fixed it in dev

**Comment by Kiyaku** [comment]
Oh heh, i shall be patient!

**Comment by bookerthegeek** [comment]
I look forward to the day i can make my players life more hellish.

Thanks for everything you do.

**Comment by jaredlll08** [comment]
http://ci.blamejared.com/job/Modtweaker/8/

Go ahead and test :)

Please don't release this version, just tell me if it works etc

**Comment by Kiyaku** [comment]
Awesome thanks a lot! 
I only tried the centrifuge and moistener so far. 
Centrifuge seems to work great, recipes work and show up in JEI.
Moistener custom recipes work too but don't show up in JEI. 

Using the same recipes as i posted above. I can try out the other machines in a bit! 

-SC

**Comment by bookerthegeek** [comment]
Also got mine to work, and to show up in JEI. You got a PayPal @jaredlll08 ?

**Comment by jaredlll08** [comment]
cool, if it all works (I'll take a look at the moistener issue) then it should all be working in the next release :)

@bookerthegeek My paypal is Jluboff8@gmail.com :)

**Comment by bookerthegeek** [comment]
Thanks, and done.
