### ISSUE TITLE
TConstruct Fuel

### ISSUE THREAD

**Issue by MrByryndyk** [jaredlll08/ModTweaker#450]
#### What happens:
"TemperatureAmount" and "Time in Ticks" do not work when adding new fuel.
If you do not specify these parameters - the temperature is 300, this is a very low temperature. But the script works fine.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/yZbL4q8M

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/kWYuu9Cn
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24
- ModTweaker: 2.0.11
- MTLib: 1.0.2

**Comment by jaredlll08** [comment]
The time in ticks param doesn't exist. The other issue about the fuel temp has been fixed in code.

**Comment by MrByryndyk** [comment]
I compiled the mod from the source code. But the temperature still does not change, 300

**Comment by jaredlll08** [comment]
TIC bug, it shows the liquids temperature and not the registry temperature,
they know about it.
